### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JustinGOSSES** [morganjwilliams/pyrolite#20]
**Describe the bug**
The link to "dimensionality reduction" on https://pyrolite.readthedocs.io/en/master/usage/eg/plotting/spider.html under the heading "see also" doesn't go anywhere. 

**To Reproduce**
1. navigate to: https://pyrolite.readthedocs.io/en/master/usage/eg/plotting/spider.html
2. click on "Dimensional Reduction".
3. It takes you to this link which doesn't exist: https://pyrolite.readthedocs.io/en/master/usage/eg/plotting/lambdadimreduction.html

**Expected behavior**
Expected to go to a page on dimensionality reduction.

**Environment:**
Master of docs on September 15th, 2019 on chrome browser.

**Additional Context**

**Comment by morganjwilliams** [comment]
Thanks for the bug report! 

This is now fixed with 812652808d4819953b45cb4887837784cc3f8dee on develop (along with another outdated link on the same page, fixed with 17eb5006beaa0e8b8ed188586dec08eddecd3a8f), and the master version of the docs will be updated with the next release. Currently the default target for the docs is develop (to get more examples out and update API docs between releases), so this should now be live.
