### ISSUE TITLE
Docs: Outdated `latest` version persists on RTD (Problem loading pyrolite.plot.tern cannot import name 'ABC_to_xy')

### ISSUE THREAD

**Issue by PennyWieser** [morganjwilliams/pyrolite#66]
I'm using pyrolite 0.3.0 and matplotlib v'3.4.1'

I'm following the ternary plot example,  when I run this cell:

import pyrolite
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pyrolite.plot.tern import ternary

I get the error:
----> 5 from pyrolite.plot.tern import ternary

~\anaconda3\lib\site-packages\pyrolite\plot\tern.py in <module>
      3 import ternary as pyternary
      4 import logging
----> 5 from ..util.plot import (
      6     ABC_to_xy,
      7     __DEFAULT_CONT_COLORMAP__,

ImportError: cannot import name 'ABC_to_xy' from 'pyrolite.util.plot' (C:\Users\penny\anaconda3\lib\site-packages\pyrolite\util\plot\__init__.py)

Is this a me issue or  a pyrolite issue?

**Comment by morganjwilliams** [comment]
Hey @PennyWieser - I'll have a look at this one later today and get back to you, it could definitely be a bug.

**Comment by morganjwilliams** [comment]
Hey Penny, can you confirm you're using 0.3.0, and which example you're going off? `pyrolite.plot.tern` was removed in [v0.2.4](https://github.com/morganjwilliams/pyrolite/releases/tag/0.2.4). I found an old mention of `pyrolite.plot.tern` in the docs examples description (this is an error) but otherwise can't find where you might be seeing it in current docs.

**Comment by PennyWieser** [comment]
I was following this one: 
![image](https://user-images.githubusercontent.com/65668673/140457796-66dfb304-c89a-4145-a8c2-a2180c17a4a3.png)
The first loading sell (maybe thats the error you mention)
Defo on 0.3.0

**Comment by morganjwilliams** [comment]
Ah - I see the issue! I swapped the docs versions being built a long time ago. `latest` still exists but hasn't been built since 0.0.17 - and I'll need to make sure I turn it off. [pyrolite.rtfd.io](pyrolite.rtfd.io) should by default take you to the latest stable ('main') version, and if you're curious about recent changes, check out the [develop version](https://pyrolite.readthedocs.io/en/develop/).

**Comment by morganjwilliams** [comment]
@PennyWieser - in the meantime, please have a look at the [current ternary example](https://pyrolite.readthedocs.io/en/main/examples/plotting/ternary.html), and let me know if that still gives you issues.

**Comment by PennyWieser** [comment]
My bad sorry this was the first page that came up when I googled ternary plot python!

**Comment by morganjwilliams** [comment]
The google part is my bad; I thought latest had disappeared into the ether!

**Comment by morganjwilliams** [comment]
With the release of 0.3.1 and the odd change in the readthedocs configuration, this should now be solved. [pyrolite.readthedocs.io/en/latest/](https://pyrolite.readthedocs.io/en/latest/) should now give a HTTP 404 error - which defaults to 'Maze Found' on RTD.
